name: Main CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.myvars.outputs.BRANCH_NAME }}
      GIT_HASH_SHORT: ${{ steps.myvars.outputs.GIT_HASH_SHORT }}
      DATE_IN_SECS: ${{ steps.myvars.outputs.DATE_IN_SECS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set myvars
        id: myvars
        run: |
          branchname=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )
          dateinsecs=$(date +%s)
          githashshort=$(git rev-parse --short HEAD)
          echo "BRANCH_NAME=$branchname" >> $GITHUB_OUTPUT
          echo "GIT_HASH_SHORT=$githashshort" >> $GITHUB_OUTPUT
          echo "DATE_IN_SECS=$dateinsecs" >> $GITHUB_OUTPUT

      - name: Setup Node.js with nvm
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies (needed for key storage)
        run: sudo apt-get install libsecret-1-0

      - name: Install dependencies using Yarn
        run: yarn install

      - name: Run lint if the script is present
        run: yarn lint || echo "Lint script not found, skipping..."

      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: TEST
          TENDERLY_KEY: ${{ secrets.TENDERLY_KEY }}
          TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
          TENDERLY_USERNAME: ${{ secrets.TENDERLY_USERNAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          WEB_3_STORAGE_KEY: ${{ secrets.WEB_3_STORAGE_KEY }}

      - name: Build the project if the build script is present
        run: yarn build || echo "Build script not found, skipping..."
        env:
          CI: true

  scan-vuln-deps-repo:
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      ## The 'fs' scan mode requires *.lock files in order to scan for vulns
      ## and to collect license info of packages you should run npm install before.
      - name: Setup NodeJS before scanning with Trivy
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install deps before scanning with Trivy
        run: |
          yarn install
          npm install

      - name: Scan in Repo (html)
        uses: aquasecurity/trivy-action@master
        if: success() || failure()
        with:
          scan-type: fs
          scanners: vuln,secret,config
          scan-ref: .
          format: template
          template: '@/contrib/html.tpl'
          output: trivy-results-repo-${{ needs.build-and-test.outputs.GIT_HASH_SHORT }}.html
        env:
          TRIVY_USERNAME: ${{ github.repository_owner }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan in Repo (sarif)
        uses: aquasecurity/trivy-action@master
        if: success() || failure()
        with:
          scan-type: fs
          scanners: vuln,secret,config
          scan-ref: .
          format: sarif
          output: trivy-results-repo-${{ needs.build-and-test.outputs.GIT_HASH_SHORT }}.sarif
        env:
          TRIVY_USERNAME: ${{ github.repository_owner }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Repo Scan Results as Artifact
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: trivy-results-repo-${{ needs.build-and-test.outputs.DATE_IN_SECS }}
          path: trivy-results-repo-${{ needs.build-and-test.outputs.GIT_HASH_SHORT }}.*

      - name: Load Repo Scan Results (sarif) to Github
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results-repo-${{ needs.build-and-test.outputs.GIT_HASH_SHORT }}.sarif
          category: sca-vulns-repo
