name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use volta
        uses: volta-cli/action@v4
        with:
          node-version: 18.x

      - run: yarn install
      - run: yarn test

      # Install dependencies using Yarn
      - run: yarn install
      # Run lint if the script is present
      - run: yarn lint || echo "Lint script not found, skipping..."
      # Run tests
      - run: yarn test
      # Build the project if the build script is present
      - run: yarn build || echo "Build script not found, skipping..."
        env:
          CI: true
