name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18' # using Node 18
      # Install dependencies using Yarn
      - run: npm install -g yarn@4.0.0-rc.43
      - run: yarn install --frozen-lockfile
      # Run lint if the script is present
      - run: yarn lint || echo "Lint script not found, skipping..."
      # Run tests
      - run: yarn test
      # Build the project if the build script is present
      - run: yarn build || echo "Build script not found, skipping..."
        env:
          CI: true
