name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1 # Using pnpm action to setup pnpm
        with:
          version: latest # You can specify a version of pnpm if needed
      - run: pnpm install --frozen-lockfile # Using pnpm instead of npm
      - run: pnpm run lint --if-present
      - run: pnpm test
      - run: pnpm run build --if-present
        env:
          CI: true
